version: "3.7"  # Optional, can be removed

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"   # Expose Postgres port if you need to access it outside the container

  app:
    image: umukoro-node-app
    ports:
      - "4000:3000"   # Map container port 3000 to host port 3000
    depends_on:
      - db            # Ensure the app service starts after the db service
